### ISSUE TITLE
The active theme is broken. Reverting to the default theme.

### ISSUE THREAD

**Issue by brentnorris** [jpen365/five-hacks-for-twenty-seventeen#1]
Got an undeclared statement in functions.php after updating twenty seventeen parent theme.

**Comment by jpen365** [comment]
I haven't been able to duplicate the issue. I've updated to WP 4.8 and updated Twenty Seventeen to the latest version both locally (LAMP, PHP 5.6) and with a web host (LEMP, PHP 7). 

Can you paste the error here and share more information about the environment where you're seeing the issue?

**Comment by brentnorris** [comment]
Will try. I already removed the folder and did some cleanup. Will try and reproduce. Sorry I didn't copy the error when it happened...

**Comment by brentnorris** [comment]
Copied the folder back to themes folder and previewed. Got this: 

Fatal error: Cannot redeclare twentyseventeen_excerpt_more() (previously declared in /wp-content/themes/five-hacks-for-twenty-seventeen-1.12/functions.php:28) in /wp-content/themes/twentyseventeen/functions.php on line 355

Here's my functions.php

/*
Theme Name:     Five Hacks for Twenty Seventeen
Theme URI:      http://premium.wpmudev.org/blog
Description:    A Twenty Seventeen child theme developed to demonstrate how to implement five theme customizations: a custom social links menu, a personalized site footer message, dynamic one page navigation, custom front page sidebars, and a large featured image.
Author:         Jon Penland
Author URI:     https://www.jonpenland.com
License:        GNU General Public License v2 or later
License URI:    http://www.gnu.org/licenses/gpl-2.0.html
Template:       twentyseventeen
Version:        1.11
*/

/* Button Code 
.button {
  display: inline-block;
  border-radius: 2px;
  background-color: #767676;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 28px;
  padding: 20px;
  width: 200px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\3333';
  position: absolute;
  opacity: 30;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}


/* Force sticky navigation into position */
#page-header {
  margin-bottom: 0 !important;
}
/* Force header image to full height */
#custom-header-media {
  height: 100vh;
  max-height: 100%;
  overflow: show;
  position: relative;
}

@media screen and (max-width: 48em) {
  .has-header-image.twentyseventeen-front-page .site-branding,
  .has-header-video.twentyseventeen-front-page .site-branding,
  .has-header-image.home.blog .site-branding,
  .has-header-video.home.blog .site-branding {
    bottom: 0;
    display: block;
    left: 0;
    height: auto;
    padding-top: 0;
    position: absolute;
    width: 100%;
  }
}

**Comment by jpen365** [comment]
That looks like style.css. Can double check the file?

**Comment by brentnorris** [comment]
hah, sorry...

<?php

// Enqueue parent theme styles and child theme stylesheet
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style', get_stylesheet_directory_uri() . '/style.css', array('parent-style') );
}

// Enqueue child them js file
add_action( 'wp_enqueue_scripts', 'child_theme_js' );
function child_theme_js() {
  wp_enqueue_script( 'child-theme-js' , get_stylesheet_directory_uri() . '/child-theme-js.js' , array( 'twentyseventeen-global' ) , false , true );
}

// Add child theme selectors for color schemes.
function dynamic_seventeen_custom_colors_css( $css, $hue, $saturation ) {
    $css .= '
    .colors-custom .content-menu > article:not(.has-post-thumbnail),
    .colors-custom .content-menu > section:not(.has-post-thumbnail) {
        border-top-color: hsl( ' . $hue . ', ' . $saturation . ', 87% ); /* base: #ddd; */
    }';
    return $css;
}
add_filter( 'twentyseventeen_custom_colors_css', 'dynamic_seventeen_custom_colors_css', 10, 3 );

/** * Replaces "[...]" (appended to automatically generated excerpts) with ... and * a 'Continue reading' link. * * @since Twenty Seventeen 1.0 * * @return string 'Continue reading' link prepended with an ellipsis. */
function twentyseventeen_excerpt_more( $link ) {	if ( is_admin() ) {		return $link;	}	$link = sprintf( '<p class="link-more"><a href="%1$s" class="more-link">%2$s</a></p>',		esc_url( get_permalink( get_the_ID() ) ),		/* translators: %s: Name of current post */		sprintf( __( 'Learn More <span class="screen-reader-text"> "%s"</span>', 'twentyseventeen' ), get_the_title( get_the_ID() ) )	);	return ' &hellip; ' . $link;
}
add_filter( 'excerpt_more', 'twentyseventeen_excerpt_more' );

//Change the number of pages on the front page
function childtheme_front_page_sections() {
    return 6;
}
add_filter( 'twentyseventeen_front_page_sections', 'childtheme_front_page_sections' );


/* Remove query strings from static resources
function _remove_script_version( $src ){
$parts = explode( '?ver', $src );
return $parts[0];
}
add_filter( 'script_loader_src', '_remove_script_version', 15, 1 );
add_filter( 'style_loader_src', '_remove_script_version', 15, 1 );


/*Defer slow loading scripts till last
function defer_parsing_of_js ( $url ) {
if ( FALSE === strpos( $url, '.js' ) ) return $url;
if ( strpos( $url, 'jquery.js' ) ) return $url;
return "$url' defer ";
}
add_filter( 'clean_url', 'defer_parsing_of_js', 11, 1 );

**Comment by brentnorris** [comment]
`<?php

// Enqueue parent theme styles and child theme stylesheet
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style', get_stylesheet_directory_uri() . '/style.css', array('parent-style') );
}

// Enqueue child them js file
add_action( 'wp_enqueue_scripts', 'child_theme_js' );
function child_theme_js() {
  wp_enqueue_script( 'child-theme-js' , get_stylesheet_directory_uri() . '/child-theme-js.js' , array( 'twentyseventeen-global' ) , false , true );
}

// Add child theme selectors for color schemes.
function dynamic_seventeen_custom_colors_css( $css, $hue, $saturation ) {
    $css .= '
    .colors-custom .content-menu > article:not(.has-post-thumbnail),
    .colors-custom .content-menu > section:not(.has-post-thumbnail) {
        border-top-color: hsl( ' . $hue . ', ' . $saturation . ', 87% ); /* base: #ddd; */
    }';
    return $css;
}
add_filter( 'twentyseventeen_custom_colors_css', 'dynamic_seventeen_custom_colors_css', 10, 3 );

/** * Replaces "[...]" (appended to automatically generated excerpts) with ... and * a 'Continue reading' link. * * @since Twenty Seventeen 1.0 * * @return string 'Continue reading' link prepended with an ellipsis. */
function twentyseventeen_excerpt_more( $link ) {	if ( is_admin() ) {		return $link;	}	$link = sprintf( '<p class="link-more"><a href="%1$s" class="more-link">%2$s</a></p>',		esc_url( get_permalink( get_the_ID() ) ),		/* translators: %s: Name of current post */		sprintf( __( 'Learn More <span class="screen-reader-text"> "%s"</span>', 'twentyseventeen' ), get_the_title( get_the_ID() ) )	);	return ' &hellip; ' . $link;
}
add_filter( 'excerpt_more', 'twentyseventeen_excerpt_more' );

//Change the number of pages on the front page
function childtheme_front_page_sections() {
    return 6;
}
add_filter( 'twentyseventeen_front_page_sections', 'childtheme_front_page_sections' );


/* Remove query strings from static resources
function _remove_script_version( $src ){
$parts = explode( '?ver', $src );
return $parts[0];
}
add_filter( 'script_loader_src', '_remove_script_version', 15, 1 );
add_filter( 'style_loader_src', '_remove_script_version', 15, 1 );


/*Defer slow loading scripts till last
function defer_parsing_of_js ( $url ) {
if ( FALSE === strpos( $url, '.js' ) ) return $url;
if ( strpos( $url, 'jquery.js' ) ) return $url;
return "$url' defer ";
}
add_filter( 'clean_url', 'defer_parsing_of_js', 11, 1 );
`

**Comment by jpen365** [comment]
Your theme's functions.php includes a lot of stuff that the original [functions.php](https://github.com/jpen365/five-hacks-for-twenty-seventeen/blob/master/functions.php) does not include and the errors are coming from the extra code. I've quickly cleaned up the syntax errors that PHP reported to me. Try replacing everything in your current functions.php file with this:

```<?php

// Enqueue parent theme styles and child theme stylesheet
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
wp_enqueue_style( 'child-style', get_stylesheet_directory_uri() . '/style.css', array('parent-style') );
}

// Enqueue child them js file
add_action( 'wp_enqueue_scripts', 'child_theme_js' );
function child_theme_js() {
wp_enqueue_script( 'child-theme-js' , get_stylesheet_directory_uri() . '/child-theme-js.js' , array( 'twentyseventeen-global' ) , false , true );
}

// Add child theme selectors for color schemes.
function dynamic_seventeen_custom_colors_css( $css, $hue, $saturation ) {
$css .= '
.colors-custom .content-menu > article:not(.has-post-thumbnail),
.colors-custom .content-menu > section:not(.has-post-thumbnail) {
border-top-color: hsl( ' . $hue . ', ' . $saturation . ', 87% ); /* base: #ddd; */
}';
return $css;
}
add_filter( 'twentyseventeen_custom_colors_css', 'dynamic_seventeen_custom_colors_css', 10, 3 );

sprintf( __( 'Learn More "%s"', 'twentyseventeen' ), get_the_title( get_the_ID() )  );  return ' … ' . $link;

add_filter( 'excerpt_more', 'twentyseventeen_excerpt_more' );
//Change the number of pages on the front page
function childtheme_front_page_sections() {
return 6;
}
add_filter( 'twentyseventeen_front_page_sections', 'childtheme_front_page_sections' );```

**Comment by jpen365** [comment]
Note that you'll still need the opening <?php tag. It looks like Github stripped that out when I pasted the contents of functions.php above.

**Comment by brentnorris** [comment]
Thanks for that Jon, really appreciate the help.

I replaced the code -result:

Parse error: syntax error, unexpected '`' in /home/brent403/public_html/wp-content/themes/five-hacks-for-twenty-seventeen-1.12/functions.php on line 34

If this is something that I added, please ignore and consider resolved. I can add/remove hooks and filters. Forgot that I had made changes in the functions.php. So probably not your code. Especially since I seem to be the only one reporting an issue. ;)

**Comment by brentnorris** [comment]
To be clear, the last error and previous syntax errors were not from jpen365's "five-hacks-for-twenty-seventeen" child theme. 

Many thanks Jon!
